#! /bin/bash

#SBATCH --job-name=group_differences_palm
#SBATCH --output=/data/project/BEACONB/logs/group_differences_palm.out
#SBATCH --export=none
#SBATCH --cpus-per-task=1
#SBATCH --mem=25G

source /software/system/modules/latest/init/bash
module use /software/system/modules/NaN/generic
module purge
module load nan

module load fsl/6.0.5.2
module load miniconda/3
module load palm/20220826

echo "Running on $HOSTNAME"
conda activate neuroimaging
python3 /data/project/BEACONB/task_fmri/socio-emotion-cognition/task_fmri/modelling/test_palm.py -t happy -p 1000