#! /bin/bash

#SBATCH --job-name=palm_eft
#SBATCH --output=/data/project/BEACONB/logs/eft_2ndlevel.out
#SBATCH --export=none
#SBATCH --cpus-per-task=1
#SBATCH --mem=25G

source /software/system/modules/latest/init/bash
module use /software/system/modules/NaN/generic
module purge
module load nan

module load fsl/6.0.5.2
module load miniconda/3
module load palm/20220826

echo "Running on $HOSTNAME"
conda activate neuroimaging
python3 /data/project/BEACONB/task_fmri/socio-emotion-cognition/task_fmri/modelling/second_level_palm.py -t eft -p 1000