#! /bin/bash

#SBATCH --job-name=happy_group_diff
#SBATCH --output=/data/project/BEACONB/logs/happy_group_diff.out
#SBATCH --export=none
#SBATCH --cpus-per-task=6
#SBATCH --mem=5G

source /software/system/modules/latest/init/bash
module use /software/system/modules/NaN/generic
module purge
module load nan

module load fsl/6.0.5.2
module load miniconda/3
module load palm/20220826

echo "Running on $HOSTNAME"
conda activate neuroimaging
python3 /data/project/BEACONB/task_fmri/socio-emotion-cognition/task_fmri/modelling/group_difference_palm.py -t happy -p 1000